// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnkaisfsrluezukgblsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFua2Fpc2Zzcmx1ZXp1a2dibHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTA4NjMsImV4cCI6MjA3MzM2Njg2M30.IsyIXtRscJ_glvwDU31M76om9voc5i-lVLvU2WDfoUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});